### ISSUE TITLE
Add a TypeScript definition file

### ISSUE THREAD

**Issue by radu-matei** [GoogleChromeLabs/asyncify#2]
First of all, thank you for this really great module!
Trying to use this with TypeScript, it requires a definition file for the types and functions exported.

The definition file below follows [the Mozilla docs for `instantiate`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiate), [`instantiateStreaming`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming),  and [the definitions from TypeScript](https://github.com/microsoft/TypeScript/blob/668bbc64ff73e5910f86a54e0bc6d3fd5b1b238d/lib/lib.dom.d.ts#L19125-L19127): 

```typescript
declare module "asyncify-wasm" {
  class Instance extends WebAssembly.Instance {
    constructor(module: WebAssembly.Module, imports: WebAssembly.Imports);
  }

  function instantiate(
    bytes: BufferSource,
    importObject?: WebAssembly.Imports
  ): Promise<WebAssembly.WebAssemblyInstantiatedSource>;

  function instantiate(
    moduleObject: WebAssembly.Module,
    importObject?: WebAssembly.Imports
  ): Promise<WebAssembly.Instance>;

  function instantiateStreaming(
    response: Response | PromiseLike<Response>,
    importObject?: WebAssembly.Imports
  ): Promise<WebAssembly.WebAssemblyInstantiatedSource>;
}

```
Having the above in `index.d.ts` at the root of the module satisfies the compiler checks.
I have [a branch](https://github.com/radu-matei/asyncify/tree/add-ts-declaration) with this change that I'd be happy to contribute upstream.

That being said, including the definitions in the module means they will have to be kept in sync if the public API of the module changes - and I understand if this is out of scope for the project. 
(If this ends up not being part of the project, the `tsconfig` file for a TypeScript project can be modified to `include` the path to a definition file with the above contents.)

Thanks!

**Comment by RReverser** [comment]
@radu-matei Oh hi! Sorry I missed your issue, subscribed to the repo now to avoid this happening again.

I do agree TS definitions would be useful, and it's something I had to work around myself. I'll happily accept a PR!

In the future, we might try to add JSDoc comments and autogenerate definitions, but, on the other hand, this API is meant to be intentionally stable to match the `WebAssembly` one, so I think this would be an overkill.

For now, a PR with your definitions would be more than enough!

**Comment by RReverser** [comment]
Note that another thing you could do to avoid having to repeat params / results definitions is to declare functions as `const` + `typeof` instead, e.g.:

```ts
const instantiate: typeof WebAssembly.instantiate;
```
