### ISSUE TITLE
asyncify-wasm 1.2.0 release seems to be missing dist?

### ISSUE THREAD

**Issue by jrandall** [GoogleChromeLabs/asyncify#4]
## Expected Behavior
Can use asyncify-wasm by updating 1.1.2 to 1.2.0

## Actual Behavior
1.1.2 works but 1.2.0 does not

Note that: https://unpkg.com/asyncify-wasm@1.1.2/dist/asyncify.mjs has content but https://unpkg.com/asyncify-wasm@1.2.0/dist/asyncify.mjs is missing

## Steps to Reproduce the Problem

1. Update package from 1.1.2 to 1.2.0

## Specifications

- Version: 1.2.0

**Comment by RReverser** [comment]
Fixed in 1.2.1, thanks.
